BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TIMESHEET" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"CUSTOMER"	INTEGER NOT NULL,
	"TYPE"	INTEGER NOT NULL,
	"DESCRIPTION"	INTEGER,
	"PROJECT"	INTEGER,
	"START"	REAL,
	"END"	REAL
);
CREATE TABLE IF NOT EXISTS "TYPE" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"NAME"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "CUSTOMER" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"NAME"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "PROJECT" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"NAME"	INTEGER NOT NULL
);

INSERT INTO "TYPE" ("ID","NAME") VALUES (1,'Administration'),
 (2,'Arbeitsweg'),
 (3,'Meeting'),
 (4,'Projekt'),
 (5,'Reisezeit'),
 (6,'Schulung'),
 (7,'Bildung'),
 (8,'Trakingpunkte');
INSERT INTO "CUSTOMER" ("ID","NAME") VALUES (1,'DA'),
 (2,'CT'),
 (3,'SP'),
 (4,'ST');
INSERT INTO "PROJECT" ("ID","NAME") VALUES (1,'ST-ITD2818'),
 (2,'DA-eNB'),
 (3,'ST-ITD3599'),
 (4,'ST-ITD3628'),
 (5,'DA-IMM'),
 (6,'DA-PantLayout2'),
 (7,'DA-upgrade-e62'),
 (8,'ST-ITD3566'),
 (9,'DA-STEP'),
 (10,'DA-eAWG_KPI'),
 (11,'DA-IntegrationAM'),
 (12,'ST-ITD3970'),
 (13,'ST-tangenerator'),
 (14,'CT-agile-ws'),
 (15,'CT-SLM'),
 (16,'SP-erweiterung');
COMMIT;
